# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ituuz
subtitle: 专注于游戏开发
description: 积土而为山，积水而为海。
author: ituuz
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://ituuz.com/child' and root as '/child/'
url: http://ituuz.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-reloaded
avatar: /uploads/avatar.png
## duoshuo
duoshuo_shortname: ituuz
## baidu_analytics
baidu_analytics: f8f404eab4896771d7002e461ae69012

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: 
    - https://e.coding.net/ituuz/ituuz.coding.me.git
    - https://github.com/yue19870813/yue19870813.github.io.git
  branch: master

